# Publish all joint states -----------------------------------
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000  


omnidrive_velocity_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
        - omni_joint_x
        - omni_joint_y
        - omni_joint_theta

omnidrive_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
        - omni_joint_x
        - omni_joint_y
        - omni_joint_theta

joints_position_controller:
    type: position_controllers/JointGroupPositionController
    joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6

joints_velocity_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
        

gripper_position_controller:
    type: position_controllers/GripperActionController
    joint: right_finger_bottom_joint
    action_monitor_rate: 100

gazebo_ros_control:
    pid_gains:
        right_finger_bottom_joint: {p: 10.0, i: 0.0, d: 0.0} 
        right_finger_tip_joint: {p: 1.0, i: 0.0, d: 0.0} 
        left_finger_bottom_joint: {p: 10.0, i: 0.0, d: 0.0} 
        left_finger_tip_joint: {p: 1.0, i: 0.0, d: 0.0}
