<?xml version="1.0"?>
<robot name="dinova" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:arg name="robot_id" default="" />
    <xacro:arg name="load_gripper" default="true"/>
    <xacro:arg name="dingo_real_urdf" default="true"/>
    <xacro:arg name="lidar" default="true"/>

    <xacro:property name="platform_height" value="0.279" />

    <!-- Add dingo -->
    <xacro:if value="$(arg dingo_real_urdf)">
        <xacro:include filename="$(find dinova_description)/urdf/real_dingo-o.urdf.xacro" />
    </xacro:if>
    <xacro:unless value="$(arg dingo_real_urdf)">
        <xacro:include filename="$(find dinova_description)/urdf/dingo_omni_macro.xacro"/>
        <xacro:dingo_omni prefix="$(arg robot_id)"/>
        
        <link name="world"/>
        <joint name="$(arg robot_id)world_link" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="world"/>
            <child link="$(arg robot_id)base_link"/>
        </joint>
    </xacro:unless>


    <!-- Add kinova -->
    <xacro:include filename="$(find dinova_description)/urdf/kinova_macro.xacro"/>
    <xacro:kinova prefix="$(arg robot_id)"/>


    <!-- Add kinova gripper -->
    <xacro:if value="$(arg load_gripper)">
        <xacro:include filename="$(find dinova_description)/urdf/kinova_gripper_macro.xacro"/>
        <xacro:kinova_gripper prefix="$(arg robot_id)"/>

        <joint name="$(arg robot_id)arm_gripper_base_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="$(arg robot_id)dummy_link"/>
            <child link="$(arg robot_id)gripper_base_link"/>
            <axis xyz="0 0 0"/>
        </joint>
    </xacro:if>

    <!-- Check lidar option -->
    <xacro:if value="$(arg lidar)">
        <!-- Metal platform -->
        <link name="$(arg robot_id)platform_link">
            <visual>
            <origin rpy="0 0 0" xyz="0 0 ${platform_height/2.0}"/>
            <geometry>
                <cylinder length="${platform_height}" radius="0.08"/>
            </geometry>
            <material name="gray">
                <color rgba="0.1 0.1 0.1 0.8"/>
            </material>
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 ${platform_height/2.0}"/>
                <geometry>
                    <cylinder length="${platform_height}" radius="0.08"/>
                </geometry>
            </collision>
            <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="0.4"/>
            <inertia ixx="0.0003234" ixy="0" ixz="0" iyy="0.0003234" iyz="0" izz="0.0004901"/>
            </inertial>
         </link>

        <!-- Connection between dingo and platform -->
        <joint name="$(arg robot_id)platform_mount_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="$(arg robot_id)front_b_mount"/>
            <child link="$(arg robot_id)platform_link"/>
        </joint>

        

        <!-- Connection between dingo and kinova -->
        <joint name="$(arg robot_id)arm_mount_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0.0399 0 ${platform_height}"/>
            <parent link="$(arg robot_id)front_b_mount"/>
            <child link="$(arg robot_id)kinova_base_link"/>
        </joint>

        <!-- <xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro"/>
        <xacro:VLP-16 parent="$(arg robot_id)front_b_mount" name="$(arg robot_id)velodyne" topic="/$(arg robot_id)/velodyne_points" hz="10" samples="440" gpu="false" min_range="0.4" >
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:VLP-16> -->

    </xacro:if>
    <xacro:unless value="$(arg lidar)">
        <!-- Connection between dingo and kinova -->
        <joint name="$(arg robot_id)arm_mount_joint" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="$(arg robot_id)front_b_mount"/>
            <child link="$(arg robot_id)kinova_base_link"/>
        </joint>
    </xacro:unless>
</robot>
